# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(1064, 811)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 260, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.xc = QtWidgets.QLineEdit(self.centralwidget)
        self.xc.setGeometry(QtCore.QRect(240, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xc.setFont(font)
        self.xc.setObjectName("xc")
        self.yc = QtWidgets.QLineEdit(self.centralwidget)
        self.yc.setGeometry(QtCore.QRect(240, 80, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.yc.setFont(font)
        self.yc.setObjectName("yc")
        self.rad = QtWidgets.QLineEdit(self.centralwidget)
        self.rad.setGeometry(QtCore.QRect(240, 140, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rad.setFont(font)
        self.rad.setObjectName("rad")
        self.ps = QtWidgets.QLineEdit(self.centralwidget)
        self.ps.setGeometry(QtCore.QRect(240, 200, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ps.setFont(font)
        self.ps.setObjectName("ps")
        self.noise = QtWidgets.QLineEdit(self.centralwidget)
        self.noise.setGeometry(QtCore.QRect(240, 260, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.noise.setFont(font)
        self.noise.setObjectName("noise")
        self.plot = MplWidget(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(380, 10, 681, 511))
        self.plot.setObjectName("plot")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 470, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.applyFit = QtWidgets.QCheckBox(self.centralwidget)
        self.applyFit.setGeometry(QtCore.QRect(240, 490, 31, 31))
        self.applyFit.setText("")
        self.applyFit.setIconSize(QtCore.QSize(32, 32))
        self.applyFit.setObjectName("applyFit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 530, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.fitResults = QtWidgets.QTextEdit(self.centralwidget)
        self.fitResults.setGeometry(QtCore.QRect(240, 530, 821, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fitResults.setFont(font)
        self.fitResults.setReadOnly(True)
        self.fitResults.setObjectName("fitResults")
        mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 21))
        self.menubar.setObjectName("menubar")
        mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "MainWindow"))
        self.label.setText(_translate("mainwindow", "Center X"))
        self.label_2.setText(_translate("mainwindow", "Center Y"))
        self.label_3.setText(_translate("mainwindow", "Radius"))
        self.label_4.setText(_translate("mainwindow", "Noise"))
        self.label_5.setText(_translate("mainwindow", "Phase Step"))
        self.label_6.setText(_translate("mainwindow", "Apply Fit"))
        self.label_7.setText(_translate("mainwindow", "Result"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainwindow = QtWidgets.QMainWindow()
    ui = Ui_mainwindow()
    ui.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())

